config/routes.rb
Rails.application.routes.draw do

  get "/export/answers", to: "surveys#export_answers"

  get "/audits/:id/:token_id/:step", to: "audits#index", as: "audits_index"
  post "/save/answers", to: "audits#save_answers", as: "audits_save_answers"
  get "/finish", to: "audits#finish", as: "audits_finish"

  resources :surveys do
    get "add/emails", to: "surveys#add_emails"
    post "send/survey", to: "surveys#send_survey_by_email"
    get "participants", to: "surveys#participants"

    get "add/sections", to: "survey_sections#add_sections"
    post "save/sections", to: "survey_sections#save_sections"
    delete "delete/section", to: "survey_sections#delete_section"
    patch "up/section", to: "survey_sections#up_section"
    patch "down/section", to: "survey_sections#down_section"
  end

  resources :questions do
    post "option/create", to: "options#create"
    get "option/edit", to: "options#edit"
    patch "option/update", to: "options#update"
    delete "option/destroy", to: "options#destroy"
  end

  resources :sections do
    post "question/create", to: "questions#create"
    get "question/edit", to: "questions#edit"
    patch "question/update", to: "questions#update"
    delete "question/destroy", to: "questions#destroy"
  end

  resources :chapters do
    get 'body/edit', to: "chapters#body"
  end

  resources :evaluations

  devise_for :users

  authenticated(:user) do
    root "pages#index", as: :authenticated_root
  end

  unauthenticated(:user) do
    root "pages#landing_page"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question

  has_rich_text :name
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: %i[create]
  before_action :set_option, only: %i[edit update destroy]

  def edit
  end

  def create
    @option = @question.options.new(option_params)

    if @option.save
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.append("question_#{@question.id}_options",
                                                  partial: 'options/option',
                                                  locals: { option: @option }) }
      end
    else
      format.html { render :new, status: :unprocessable_entity }
    end
  end

  def update
    if @option.update(option_params)
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace("option_#{@option.id}",
                                                  partial: 'options/option',
                                                  locals: { option: @option }) }
      end
    end
  end

  def destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("option_#{@option.id}") }
    end
    @option.destroy
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def option_params
    params.require(:option).permit(:name)
  end

  def set_option
    @option = Option.find(params[:id])
  end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/options/_form.html.erb
<div data-controller="reset">
  <%= form_for [question, option], url: question_option_create_path(question),
        html: { class: "p-5 flex flex-col", id: "question_#{question.id}_option_form" },
        data: { action: 'submit->reset#optionForm' } do |f| %>

    <h4 class="font-bold text-center mb-5">Add options</h4>

    <div class="my-2">
      <%= f.rich_text_area :name, id: "question_#{question.id}_option", class: "p-2 text-sm border-2" %>
    </div>

    <div class="my-2 flex justify-end">
      <span class="bg-evaluationStrong rounded-lg">
        <%= f.submit class:"text-sm text-white p-2 font-semibold" %>
      </span>
    </div>

  <% end %>
</div>

app/views/options/_option.html.erb
<%= turbo_frame_tag "option_#{option.id}" do %>

  <div class="border-2 rounded-lg flex justify-between p-3 m-2">

    <div>
      <span class="text-sm">
        <%= option.name %>
      </span>
    </div>

    <div class="flex gap-5">
      <%= link_to question_option_edit_path(option.question, id: option.id) do %>
        <i class="fa-solid fa-pen text-editIcon"></i>
      <% end %>

      <%= button_to question_option_destroy_path(option.question, id: option.id), method: :delete, 
          form: {data: {turbo_confirm: "Are you sure?"}} do %>
        <i class="fa-solid fa-trash text-removeIcon"></i>
      <% end %>
    </div>

  </div>

<% end %>

app/views/options/edit.html.erb
<%= turbo_frame_tag "option_#{@option.id}" do %>
  <%= form_with(model: @option, url: question_option_update_path(id: @option.id), 
        class: "flex flex-col border-2 p-5 rounded-lg bg-footerGray") do |f| %>

  <h4 class="font-bold text-center mb-5">Edit option.</h4>

  <div class="my-3">
    <%= f.rich_text_area :name, id: "option_#{@option.id}", class: "py-5 text-sm border-2 bg-white rounded-lg" %>
  </div>

  <div class="flex justify-end gap-5 my-3">
    <span class="bg-evaluationStrong rounded-lg">
      <%= f.submit class: "text-white p-2 text-sm font-semibold" %>
    </span>
    <span class="bg-removeIcon rounded-lg flex items-center">
      <%= link_to "Cancel", :back, class: "text-white p-2 text-sm font-semibold" %>
    </span>
  </div>

  <% end %>
<% end %>