config/routes.rb
Rails.application.routes.draw do

  get "/export/answers", to: "surveys#export_answers"

  get "/audits/:id/:token_id/:step", to: "audits#index", as: "audits_index"
  post "/save/answers", to: "audits#save_answers", as: "audits_save_answers"
  get "/finish", to: "audits#finish", as: "audits_finish"

  resources :surveys do
    get "add/emails", to: "surveys#add_emails"
    post "send/survey", to: "surveys#send_survey_by_email"
    get "participants", to: "surveys#participants"

    get "add/sections", to: "survey_sections#add_sections"
    post "save/sections", to: "survey_sections#save_sections"
    delete "delete/section", to: "survey_sections#delete_section"
    patch "up/section", to: "survey_sections#up_section"
    patch "down/section", to: "survey_sections#down_section"
  end

  resources :questions do
    post "option/create", to: "options#create"
    get "option/edit", to: "options#edit"
    patch "option/update", to: "options#update"
    delete "option/destroy", to: "options#destroy"
  end

  resources :sections do
    post "question/create", to: "questions#create"
    get "question/edit", to: "questions#edit"
    patch "question/update", to: "questions#update"
    delete "question/destroy", to: "questions#destroy"
  end

  resources :chapters do
    get 'body/edit', to: "chapters#body"
  end

  resources :evaluations

  devise_for :users

  authenticated(:user) do
    root "pages#index", as: :authenticated_root
  end

  unauthenticated(:user) do
    root "pages#landing_page"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/survey_section.rb
class SurveySection < ApplicationRecord
  scope :grab_objects, -> (sv_id) { where(survey_id: sv_id) }
  scope :grab_record, -> (sv_id, sc_id) { where(survey_id: sv_id).find_by(section_id: sc_id) }
  scope :set_maximum, -> (sv_id) { where(survey_id: sv_id).maximum(:order) }

  belongs_to :survey
  belongs_to :section

  before_create :configure_order

  private

  def self.check_no_repeat_records(survey, ids, new_ids)
    survey_sections = where(survey_id: survey.id)

    ids.each { |id| new_ids << id.to_i unless survey_sections.find_by(section_id: id).present? }
    new_ids
  end

  def configure_order
    surv_sect = SurveySection.where(survey_id: survey_id).order(order: :asc)
    surv_sect.empty? ? self.order = 1 : self.order = surv_sect.last.order + 1
  end

  def self.reorder_objects(id)
    survey_sections = where(survey_id: id)

    survey_sections.each.with_index do |survey_section, index|
      survey_section.update!(order: index + 1)
    end
  end
end

app/controllers/survey_sections_controller.rb
class SurveySectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_survey
  before_action :set_survey_section, except: %i[add_sections save_sections]

  def add_sections; end

  def save_sections
    ids = params[:sections][:ids].reject { |id| id.empty? }
    new_ids = SurveySection.check_no_repeat_records(@survey, ids, [])

    return if new_ids.empty?

    new_ids.each do |id|
      @survey_section = SurveySection.new(survey_id: @survey.id, section_id: id)
      @survey_section.save
    end
    set_turbo_stream
  end

  def delete_section
    @survey_section.destroy
    SurveySection.reorder_objects(@survey.id)

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{params[:id]}") }
    end
  end

  def up_section
    @prev_surv_sec = SurveySection.grab_objects(@survey.id).find_by(order: @survey_section.order - 1)
    @survey_section.update!(order: @survey_section.order - 1)
    @prev_surv_sec.update!(order: @prev_surv_sec.order + 1)
    set_turbo_stream
  end

  def down_section
    @next_surv_sec = SurveySection.grab_objects(@survey.id).find_by(order: @survey_section.order + 1)
    @survey_section.update!(order: @survey_section.order + 1)
    @next_surv_sec.update!(order: @next_surv_sec.order - 1)
    set_turbo_stream
  end

  private

  def set_survey
    @survey = Survey.find(params[:survey_id])
  end

  def set_turbo_stream
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.replace('sections',
                                                partial: 'survey_sections/survey_sections',
                                                locals: { survey: Survey.find(@survey.id) }) }
    end
  end

  def set_survey_section
    @survey_section = SurveySection.grab_record(@survey.id, params[:id])
  end
end

app/helpers/survey_sections_helper.rb
module SurveySectionsHelper
end

app/views/survey_sections/_survey_section.html.erb
<div id="<%= section.id %>" class="flex border-2 p-5 my-5 rounded-lg shadow-lg items-center">

  <div class="flex flex-col justify-center items-center mr-5 gap-2">
    <% if SurveySection.grab_record(survey.id, section.id).order != 1 %>
      <%= button_to survey_up_section_path(survey, id: section.id), method: :patch do %>
        <i class="fas fa-arrow-circle-up"></i>
      <% end %>
    <% end %>

    <% if SurveySection.grab_record(survey.id, section.id).order != SurveySection.set_maximum(survey.id) %>
      <%= button_to survey_down_section_path(survey, id: section.id), method: :patch do %>
        <i class="fas fa-arrow-circle-down"></i>
      <% end %>
    <% end %>
  </div>

  <div class="w-8/12 flex flex-col mr-5">
    <span class="font-semibold"><%= section.name %></span>
    <span class="text-sm"><%= section.description %></span>
  </div>

  <div class="w-3/12 mr-5">
    <span class="font-semibold"> <%= time_ago_in_words(section.created_at) %> </span>
  </div>

  <div class="w-1/12 flex justify-end mr-5">
    <%= button_to survey_delete_section_path(survey, id: section.id), id: "remove_section_icon", method: :delete,
     form: { data: { turbo_confirm: "Are you sure?" } } do %>
      <i class="fa-solid fa-trash text-removeIcon"></i>
    <% end %>
  </div>

</div>

app/views/survey_sections/_survey_sections.html.erb
<%= turbo_frame_tag 'modal' %>
<section id="sections" class="border-2 w-9/12 mx-auto flex flex-col rounded-lg shadow-lg my-20 p-10">

  <%= turbo_frame_tag 'participants' do %>
    <div class="flex justify-end mb-5">

      <%= button_to survey_participants_path(survey), method: :get do %>
        <i class="fas fa-users text-surveyStrong text-2xl mr-5"></i>
      <% end %>

      <%= button_to survey_add_sections_path(survey), method: :get, data: { turbo_frame: "modal" } do %>
        <span class="bg-surveyStrong font-semibold text-white shadow-lg p-2 rounded-lg">
          Add sections
        </span>
      <% end %>
    </div>

    <div>
      <% survey.sections.order(order: :asc).each do |section| %>
        <%= render "survey_sections/survey_section", {section: section, survey: survey} %>
      <% end %>
    </div>
  <% end %>
</section>

app/views/survey_sections/add_sections.html.erb
<%= render 'shared/modal', title: "All sections." do %>

  <%= form_with(url: survey_save_sections_path(@survey), data: { controller: "reset", action: "submit->reset#resetForm" }) do |f| %>

    <div class="flex flex-col h-96 my-5 p-5 overflow-y-auto">
      <%= collection_check_boxes(:sections, :ids, Section.all, :id, :name) do |b| %>
        <div class="flex">
          <%= b.check_box class:"hidden peer" %>
          <%= b.label class:"border-2 text-white font-semibold rounded-lg w-full my-2 peer-checked:check-user-box" do %>
            <div class="flex items-center">
              <div class="w-20">
                <%= image_tag("Upload.png", class: "object-fit h-full w-full") %>
              </div>

              <div class="flex flex-col ml-5">
                <span>
                  <%= b.object.name %>
                </span>
                <span>
                  <%= b.object.description %>
                </span>
              </div>

            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="flex py-2 justify-end gap-5">
      <span class="bg-evaluationStrong p-2 rounded-lg">
        <%= f.submit 'Add sections', class:"text-white font-semibold" %>
      </span>
      <span class="bg-removeIcon p-2 rounded-lg">
        <%= link_to 'Cancel', :back, class:"text-white font-semibold" %>
      </span>
    </div>

  <% end %>

<% end %>