config/routes.rb
Rails.application.routes.draw do

  get "/export/answers", to: "surveys#export_answers"

  get "/audits/:id/:token_id/:step", to: "audits#index", as: "audits_index"
  post "/save/answers", to: "audits#save_answers", as: "audits_save_answers"
  get "/finish", to: "audits#finish", as: "audits_finish"

  resources :surveys do
    get "add/emails", to: "surveys#add_emails"
    post "send/survey", to: "surveys#send_survey_by_email"
    get "participants", to: "surveys#participants"

    get "add/sections", to: "survey_sections#add_sections"
    post "save/sections", to: "survey_sections#save_sections"
    delete "delete/section", to: "survey_sections#delete_section"
    patch "up/section", to: "survey_sections#up_section"
    patch "down/section", to: "survey_sections#down_section"
  end

  resources :questions do
    post "option/create", to: "options#create"
    get "option/edit", to: "options#edit"
    patch "option/update", to: "options#update"
    delete "option/destroy", to: "options#destroy"
  end

  resources :sections do
    post "question/create", to: "questions#create"
    get "question/edit", to: "questions#edit"
    patch "question/update", to: "questions#update"
    delete "question/destroy", to: "questions#destroy"
  end

  resources :chapters do
    get 'body/edit', to: "chapters#body"
  end

  resources :evaluations

  devise_for :users

  authenticated(:user) do
    root "pages#index", as: :authenticated_root
  end

  unauthenticated(:user) do
    root "pages#landing_page"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :user

  has_one_attached :avatar, dependent: :destroy
  has_many :survey_sections, dependent: :destroy
  has_many :sections, through: :survey_sections, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :logs, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true

  before_create :set_uuid

  private

  def set_uuid
    self.uuid = SecureRandom.uuid
  end
end

app/controllers/surveys_controller.rb
require "csv"
class SurveysController < ApplicationController
  before_action :authenticate_user!
  before_action :set_survey, except: %i[ index new create ]

  def index
    @surveys = current_user.surveys.all
  end

  def show
  end

  def new
    @survey = Survey.new
  end

  def edit
  end

  def add_emails
  end

  def participants
  end

  def create
    @survey = current_user.surveys.build(survey_params)

    respond_to do |format|
      if @survey.save
        format.turbo_stream { render turbo_stream: turbo_stream.replace('surveys_all',
                                                  partial: 'surveys/surveys',
                                                  locals: { surveys: Survey.all }) }

      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace('modal',
                                                  partial: 'errors/new_survey',
                                                  locals: {}) }
      end
    end
  end

  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace("survey_#{@survey.id}",
                                                  partial: 'surveys/card_survey',
                                                  locals: { survey: @survey }) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url, notice: "Survey was successfully destroyed." }
    end
  end

  def send_survey_by_email
    send_survey_params
    @log = Log.new(email: @email, status: 0, survey_id: @survey.id)
    @log.save

    SurveyMailer.with(log: @log, subject: @subject,
                      message: @message, survey: @survey).welcome_survey.deliver_later
  end

  def export_answers
    @answers = @survey.answers

    respond_to do |format|
      format.csv { send_data @answers.to_csv, filename: "#{@survey.name}-#{Date.today}.csv" }
    end
  end

  private
    def set_survey
      @survey = Survey.find(params[:id] || params[:survey_id])
    end

    def survey_params
      params.require(:survey).permit(:name, :description, :avatar)
    end

    def send_survey_params
      @email = params[:email]
      @subject = params[:subject]
      @message = params[:message]
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_card_survey.html.erb
<%= turbo_frame_tag 'modal' %>
<section id="<%= dom_id survey %>" class="border-2 w-9/12 mx-auto flex h-48 rounded-lg shadow-lg p-2 my-20">

  <div class="w-48">
    <% if survey.avatar.attached? %>
      <%= image_tag(survey.avatar, class: "object-fit h-full w-full") %>
    <% else %>
      <%= image_tag("Upload.png", class: "object-fit h-full w-full") %>
    <% end %>
  </div>

  <div class="w-full p-5">
    <p class="text-3xl font-bold text-surveyStrong">
      <%= survey.name %>
      <i class="fa-solid fa-folder-open ml-5"></i>
    </p>

    <p class="my-2 font-smibold text-surveyStrong">
        <%= survey.description %>
    </p>

    <p class="font-semibold text-sm text-surveyStrong">
        <%= survey.user.email %>
    </p>
  </div>

  <div class="flex flex-col justify-between p-2">
    <%= link_to edit_survey_path(survey), id:"edit_chapter_icon", data: {turbo_frame: 'modal'} do %>
      <i class="fa-solid fa-pen text-editIcon"></i>
    <% end %>
    <%= button_to survey_path(survey), id: "remove_chapter_icon", method: :delete,
     form: { data: { turbo_confirm: "Are you sure?" } } do %>
      <i class="fa-solid fa-trash text-removeIcon"></i>
    <% end %>

    <%= link_to survey_add_emails_path(survey), id:"send_survey", data: {turbo_frame: 'modal'} do %>
      <i class="fas fa-share"></i>
    <% end %>

    <%= button_to export_answers_path(format: "csv"), method: :get, params: { id: survey.id }, id: "export_answers" do %>
      <i class="fas fa-cloud-download"></i>
    <% end %>
  </div>
</section>

app/views/surveys/_form.html.erb
<%= form_with(model: @survey, id: "form_survey", data: { controller: "reset", action: "submit->reset#resetForm" }) do |form| %>

  <div>
    <%= render 'shared/errors', obj: @survey %>
  </div>

  <div class="flex flex-col my-3">
    <%= form.label :name, class:"text-white font-bold w-2/12" %>
    <%= form.text_field :name, class:"p-2 rounded-lg text-sm font-semibold w-full" %>
  </div>

  <div class="flex flex-col my-3">
    <%= form.label :description, class:"text-white font-bold w-2/12" %>
    <%= form.text_field :description, class:"p-2 rounded-lg text-sm font-semibold w-full" %>
  </div>

  <div class="flex items-center my-2">
    <%= form.label :avatar, class:"text-white font-bold w-2/12" %>
    <%= form.file_field :avatar, class:"text-sm rounded-lg font-semibold" %>
  </div>

  <div class="flex py-2 justify-end gap-5">
    <span class="bg-evaluationStrong p-2 rounded-lg">
      <%= form.submit class:"text-white font-semibold" %>
    </span>
    <span class="bg-removeIcon p-2 rounded-lg">
      <%= link_to 'Cancel', :back, class:"text-white font-semibold" %>
    </span>
  </div>

<% end %>

app/views/surveys/_survey.html.erb
<div id="<%= dom_id survey %>" class="border-2 w-9/12 mx-auto flex h-40 rounded-lg shadow-lg p-2 my-5">
  <div class="w-40">
    <% if survey.avatar.attached? %>
      <%= image_tag(survey.avatar, class: "object-fit h-full w-full") %>
    <% else %>
      <%= image_tag("Upload.png", class: "object-fit h-full w-full") %>
    <% end %>
  </div>

  <div class="w-full p-5">
    <p>
      Name:
      <strong class="font-semibold">
        <%= survey.name %>
      </strong>
    </p>

    <p>
      Description:
      <strong class="font-semibold">
        <%= survey.description %>
      </strong>
    </p>

    <p>
      User:
      <strong class="font-semibold">
        <%= survey.user.email %>
      </strong>
    </p>

    <div class="flex justify-end">
      <%= button_to survey_path(survey), method: :get do %>
        <div class="rounded-lg bg-surveyStrong px-5 py-2 text-white text-sm font-semibold">
          See more
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/surveys/_surveys.html.erb
<%= turbo_frame_tag 'modal' %>
<section id="surveys_all">
  <div class="py-10 flex flex-col w-full">
    <h2 class="py-5 text-3xl text-surveyStrong font-bold text-center">Surveys</h2>
    <p class="text-sm text-center text-surveyStrong font-semibold">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde excepturi 
      omnis ex provident cupiditate perferendis porro dolores possimus aut minima <br>
      ea facere, sequi molestias! Perspiciatis, magni odit? Nisi, nam placeat!
    </p>
    <div class="flex justify-center py-5">
      <%= link_to new_survey_path, id:"create_survey_welcome", data: {turbo_frame: 'modal'} do %>
        <div class="p-3 bg-surveyStrong text-white text-sm font-semibold rounded-lg">
          Create survey
        </div>
      <% end %>
    </div>
  </div>

  <div>
    <% surveys.each do |survey| %>
      <%= render "survey", survey: survey %>
    <% end %>
  </div>
</section>

app/views/surveys/_welcome.html.erb
<%= turbo_frame_tag 'modal' %>
<section class="flex justify-center items-center p-28" id="surveys_all">
  <div>

    <h1 class="text-center text-3xl font-bold text-surveyStrong">Surveys</h1>

    <p class="flex justify-center">
        <span class="font-semibold text-surveyStrong text-sm py-2">
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. 
        </span>
    </p>

    <div class="flex justify-center py-5">
        <%= image_tag("4883612.jpg", width: "500") %>
    </div>


    <p class="text-center py-2 font-semibold text-surveyStrong">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit,
        sed do eiusmod tempor incididunt ut labore et dolore <br>
        magna aliqua. At risus viverra adipiscing at in. 
    </p>

    <div class="flex justify-center my-4">
      <%= link_to new_survey_path, id:"create_survey_welcome", data: {turbo_frame: 'modal'} do %>
        <div class="p-3 bg-surveyStrong text-white text-sm font-semibold rounded-lg">
            Create survey
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/surveys/add_emails.html.erb
<%= render 'shared/modal', title: "Send survey." do %>
  <%= form_with(url: survey_send_survey_path(@survey), id: "send_survey_form", method: :post,
        class: "flex flex-col", data: { controller: "reset", action: "submit->reset#resetForm" }) do |f| %>

    <div class="flex items-center gap-5 mt-5 mb-0">
        <%= f.label :email, "Send to:", class:"text-white font-bold w-2/12" %>
        <%= f.text_field :email, class:"p-2 rounded-lg text-sm font-semibold w-full" %>
    </div>

    <div class="mt-1 mb-5">
      <span class="text-sm font-semibold text-white">In order to add an email, follow this example: user@email.com</span>
    </div>

    <div class="flex items-center gap-5 my-2">
        <%= f.label :subject, "Subject:", class:"text-white font-bold w-2/12" %>
        <%= f.text_field :subject, class:"p-2 rounded-lg text-sm font-semibold w-full" %>
    </div>

    <div class="flex flex-col gap-5 my-5">
        <%= f.label :message, "Message:", class:"text-white font-bold w-2/12" %>
        <%= f.text_area :message, class:"p-2 rounded-lg text-sm font-semibold w-full h-48" %>
    </div>

    <div class="flex py-2 justify-end gap-5">
    <span class="bg-evaluationStrong p-2 rounded-lg">
      <%= f.submit "Send survey", class:"text-white font-semibold" %>
    </span>
    <span class="bg-removeIcon p-2 rounded-lg">
      <%= link_to 'Cancel', :back, class:"text-white font-semibold" %>
    </span>
  </div>

  <% end %>
<% end %>

app/views/surveys/edit.html.erb
<%= render 'shared/modal', title: "Update survey." do %>
  <%= render 'form' %>
<% end %>

app/views/surveys/index.html.erb
<%= turbo_frame_tag 'modal' %>
<% if @surveys.any? %>
  <%= render "surveys", surveys: @surveys %>
<% else %>
  <%= render 'welcome' %>
<% end %>

app/views/surveys/new.html.erb
<%= render 'shared/modal', title: "Create survey." do %>
  <%= render 'form' %>
<% end %>

app/views/surveys/participants.html.erb
<%= turbo_frame_tag 'participants' do %>

  <div class="flex py-2 justify-end gap-5">
    <span class="bg-removeIcon p-2 rounded-lg">
      <%= link_to 'Cancel', :back, class:"text-white font-semibold" %>
    </span>
  </div>

  <div>
    <% @survey.logs.each do |log| %>
      <div class="flex flex-col border-2 my-5 p-5 shadow-lg rounded-lg">
        <p class="flex mb-2 text-sm">
          Email:
          <span class="ml-5 font-semibold text-sm">
            <%= log.email %>
          </span>
        </p>

        <p class="flex mb-2 text-sm">
          Token:
          <span class="ml-5 font-semibold text-sm">
            <%= log.token %>
          </span>
        </p>

        <p class="flex text-sm">
          Status:
            <% if log.default? %>
              <span class="ml-5 text-sm font-semibold bg-removeIcon text-white py-2 px-5 rounded-lg">
                <%= log.status.humanize %>
              </span>
            <% elsif log.sent? %>
              <span class="ml-5 text-sm font-semibold bg-chapterStrong text-white py-2 px-5 rounded-lg">
                <%= log.status.humanize %>
              </span>
            <% elsif log.process? %>
              <span class="ml-5 text-sm font-semibold bg-surveyStrong text-white py-2 px-5 rounded-lg">
                <%= log.status.humanize %>
              </span>
            <% elsif log.finish? %>
              <span class="ml-5 text-sm font-semibold bg-evaluationStrong text-white py-2 px-5 rounded-lg">
                <%= log.status.humanize %>
              </span>
            <% end %>
        </p>
      </div>
    <% end %>
  </div>
<% end%>

app/views/surveys/show.html.erb
<%= render "card_survey", survey: @survey %>
<%= render "survey_sections/survey_sections", survey: @survey %>