config/routes.rb
Rails.application.routes.draw do

  get "/export/answers", to: "surveys#export_answers"

  get "/audits/:id/:token_id/:step", to: "audits#index", as: "audits_index"
  post "/save/answers", to: "audits#save_answers", as: "audits_save_answers"
  get "/finish", to: "audits#finish", as: "audits_finish"

  resources :surveys do
    get "add/emails", to: "surveys#add_emails"
    post "send/survey", to: "surveys#send_survey_by_email"
    get "participants", to: "surveys#participants"

    get "add/sections", to: "survey_sections#add_sections"
    post "save/sections", to: "survey_sections#save_sections"
    delete "delete/section", to: "survey_sections#delete_section"
    patch "up/section", to: "survey_sections#up_section"
    patch "down/section", to: "survey_sections#down_section"
  end

  resources :questions do
    post "option/create", to: "options#create"
    get "option/edit", to: "options#edit"
    patch "option/update", to: "options#update"
    delete "option/destroy", to: "options#destroy"
  end

  resources :sections do
    post "question/create", to: "questions#create"
    get "question/edit", to: "questions#edit"
    patch "question/update", to: "questions#update"
    delete "question/destroy", to: "questions#destroy"
  end

  resources :chapters do
    get 'body/edit', to: "chapters#body"
  end

  resources :evaluations

  devise_for :users

  authenticated(:user) do
    root "pages#index", as: :authenticated_root
  end

  unauthenticated(:user) do
    root "pages#landing_page"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chapter, only: %i[ show edit update destroy ]

  def index
    @chapters = current_user.sections.grab_all_chapters
  end

  def show
  end

  def new
    @chapter = Section.new
  end

  def edit
  end

  def body
    @chapter = Section.find(params[:chapter_id])
  end

  def create
    @chapter = current_user.sections.build(chapter_params)
    @chapter.section_type = 2

    respond_to do |format|
      if @chapter.save
        format.turbo_stream { render turbo_stream: turbo_stream.replace('chapters_all',
                                                  partial: 'chapters/chapters',
                                                  locals: { chapters: Section.grab_all_chapters }) }

      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace('modal',
                                                  partial: 'errors/new_chapter',
                                                  locals: {}) }
      end
    end
  end

  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace("section_#{@chapter.id}",
                                                  partial: 'chapters/card_chapter',
                                                  locals: { chapter: @chapter }) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @chapter.destroy

    respond_to do |format|
      format.html { redirect_to chapters_url, notice: "Chapter was successfully destroyed." }
    end
  end

  private
    def set_chapter
      @chapter = Section.find(params[:id])
    end

    def chapter_params
      params.require(:section).permit(:name, :description, :body)
    end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_card_chapter.html.erb
<section id="<%= dom_id chapter %>" class="border-2 w-9/12 mx-auto flex h-48 rounded-lg shadow-lg p-2 my-20">
  <div class="w-48">
      <%= image_tag("Upload.png", class: "object-fit h-full w-full") %>
  </div>

  <div class="w-full p-5">
    <p class="text-3xl font-bold text-chapterStrong">
      <%= chapter.name %>
      <i class="fa-solid fa-square-poll-horizontal ml-5"></i>
    </p>

    <p class="my-2 font-smibold text-chapterStrong">
        <%= chapter.description %>
    </p>

    <p class="font-semibold text-sm text-chapterStrong">
        <%= chapter.user.email %>
    </p>
  </div>

  <div class="flex flex-col justify-between p-2">
    <%= link_to edit_chapter_path(chapter), id:"edit_chapter_icon", data: {turbo_frame: 'modal'} do %>
      <i class="fa-solid fa-pen text-editIcon"></i>
    <% end %>
    <%= button_to chapter_path(chapter), id: "remove_chapter_icon", method: :delete,
     form: { data: { turbo_confirm: "Are you sure?" } } do %>
      <i class="fa-solid fa-trash text-removeIcon"></i>
    <% end %>
  </div>
</section>

app/views/chapters/_chapter.html.erb
<div id="<%= dom_id chapter %>" class="border-2 w-9/12 mx-auto flex h-40 rounded-lg shadow-lg p-2 my-5">
  <div class="w-40">
    <%= image_tag("Upload.png", class: "object-fit h-full w-full") %>
  </div>

  <div class="w-full p-5">
    <p>
      Name:
      <strong class="font-semibold">
        <%= chapter.name %>
      </strong>
    </p>

    <p>
      Description:
      <strong class="font-semibold">
        <%= chapter.description %>
      </strong>
    </p>

    <p>
      User:
      <strong class="font-semibold">
        <%= chapter.user.email %>
      </strong>
    </p>

    <div class="flex justify-end">
      <%= button_to chapter_path(chapter), method: :get do %>
        <div class="rounded-lg bg-chapterStrong px-5 py-2 text-white text-sm font-semibold">
          See more
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/chapters/_chapters.html.erb
<%= turbo_frame_tag 'modal' %>
<section id="chapters_all">
  <div class="py-10 flex flex-col w-full">
    <h2 class="py-5 text-3xl text-chapterStrong font-bold text-center">Chapters</h2>
    <p class="text-sm text-center text-chapterStrong font-semibold">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde excepturi 
      omnis ex provident cupiditate perferendis porro dolores possimus aut minima <br>
      ea facere, sequi molestias! Perspiciatis, magni odit? Nisi, nam placeat!
    </p>
    <div class="flex justify-center py-5">
      <%= link_to new_chapter_path, id:"create_chapter_welcome", data: {turbo_frame: 'modal'} do %>
        <div class="p-3 bg-chapterStrong text-white text-sm font-semibold rounded-lg">
          Create chapter
        </div>
      <% end %>
    </div>
  </div>

  <div>
    <% chapters.each do |chapter| %>
      <%= render "chapter", chapter: chapter %>
    <% end %>
  </div>
</section>

app/views/chapters/_form.html.erb
<%= form_with(model: @chapter, url: url, data: { controller: "reset", action: "submit->reset#resetForm" }) do |f| %>

  <div>
    <%= render 'shared/errors', obj: @chapter %>
  </div>

  <div class="flex flex-col py-4">
    <%= f.label :name, class:"text-white font-semibold" %>
    <%= f.text_field :name, class:"p-2 rounded-lg text-sm font-semibold w-full" %>
  </div>

  <div class="flex flex-col py-4">
    <%= f.label :description, class:"text-white font-semibold" %>
    <%= f.text_field :description, class:"p-2 rounded-lg text-sm font-semibold w-full" %>
  </div>

  <div class="flex py-2 justify-end gap-5">
    <span class="bg-evaluationStrong p-2 rounded-lg">
      <%= f.submit "#{button_text}", class:"text-white font-semibold" %>
    </span>
    <span class="bg-removeIcon p-2 rounded-lg">
      <%= link_to 'Cancel', :back, class:"text-white font-semibold" %>
    </span>
  </div>
<% end %>

app/views/chapters/_welcome.html.erb
<%= turbo_frame_tag 'modal' %>
<section class="flex flex-row-reverse justify-around items-center p-32" id="chapters_all">
    <div>
        <%= image_tag("4884176.jpg", width: "500") %>
    </div>

    <div>
        <h1 class="text-center text-3xl font-bold text-chapterStrong">Chapters</h1>
        <p class="text-center py-2 font-semibold text-chapterStrong">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, <br>
            sed do eiusmod tempor incididunt ut labore et dolore <br>
            magna aliqua. At risus viverra adipiscing at in. 
        </p>

        <div class="flex justify-center my-4">
            <%= link_to new_chapter_path, id:"create_chapter_welcome", data: {turbo_frame: 'modal'} do %>
                <div class="p-3 bg-chapterStrong text-white text-sm font-semibold rounded-lg">
                    Create chapter.
                </div>
            <% end %>
        </div>
    </div>
</section>

app/views/chapters/body.html.erb
<%= turbo_frame_tag "chapter_body", class:"border-2 w-full rounded-lg py-5" do %>
  <%= form_with(model: @chapter, url: chapter_path(@chapter), class:"flex flex-col") do |f| %>

    <h3>Editing body.</h3>

    <div>
      <%= f.label :body %>
      <%= f.rich_text_area :body %>
    </div>

    <div class="flex py-2 justify-end gap-5">
      <span class="bg-evaluationStrong p-2 rounded-lg">
        <%= f.submit "Update body.", class:"text-white font-semibold" %>
      </span>
      <span class="bg-removeIcon p-2 rounded-lg">
        <%= link_to 'Cancel', :back, class:"text-white font-semibold" %>
      </span>
    </div>


  <% end %>
<% end %>

app/views/chapters/edit.html.erb
<%= render 'shared/modal', title: "Update chapter." do %>
  <%= render 'form', {url: chapter_path(@chapter), button_text: "Update."} %>
<% end %>

app/views/chapters/index.html.erb
<%= turbo_frame_tag 'modal' %>
<% if @chapters.any? %>
    <%= render "chapters", chapters: @chapters %>
<% else %>
    <%= render 'welcome' %>
<% end %>

app/views/chapters/new.html.erb
<%= render 'shared/modal', title: "Create chapter." do %>
  <%= render 'form', { url: chapters_path, button_text: "Create chapter." } %>
<% end %>

app/views/chapters/show.html.erb
<%= turbo_frame_tag 'modal' %>

<%= render "card_chapter", chapter: @chapter %>

<section class="flex p-10">
  <%= turbo_frame_tag "chapter_body", class: "border-2 w-full rounded-lg bg-footerGray p-5" do %>

    <div class="flex justify-between pb-5">
      <h3 class="text-2xl font-bold text-chapterStrong">Body</h3>
      <%= button_to chapter_body_edit_path(@chapter), method: :get do %>
        <span class="bg-chapterStrong text-white text-sm font-semibold p-3 rounded-lg">
          Edit body
        </span>
      <% end %>
    </div>

    <div>
      <% if @chapter.body.present? %>
        <%= @chapter.body %>
      <% else %>
        <p class="font-semibold">This chapter doesn't contain any content...</p>
        <p>Please, click on the <strong>Edit body</strong> button to add a new body.</p>
      <% end %>
    </div>
  <% end %>
</section>